In [1]:
#Array Slicing
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print("Array[3:6]=",arr[3:6])
print("Array[1::3]=",arr[1::3])
print("Array[::-1]=",arr[::-1])
print("Array[4::]=",arr[4::])
print("Array[5::-2]=",arr[5::-2])


Array[3:6]= [4 5 6]
Array[1::3]= [2 5 8]
Array[::-1]= [9 8 7 6 5 4 3 2 1]
Array[4::]= [5 6 7 8 9]
Array[5::-2]= [6 4 2]


In [ ]:
#SubArray
import numpy as np
twoD_arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Original array:",twoD_arr)
sub_arr=twoD_arr[:2,:2] #[:2 reprsents values of index{0,0}=1,{0,1}=2of the first row and :2 represents values of index {1,0}=5,{1,1}=6]
print("\nsub_arr=",sub_arr)
sub_arr[0,1]=100
print("\nsub Array Modified:",sub_arr)
print("\nOriginal Array Modified:",twoD_arr)


Original array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

sub_arr= [[1 2]
 [5 6]]

sub Array Modified: [[  1 100]
 [  5   6]]

sOriginal Array Modified: [[  1 100   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [10]:
#Making the copies of the Array 
import numpy as np
twoD_arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Original array:",twoD_arr)
sub_arr=twoD_arr[:2,:2].copy()  #Using copy() to create a copy of the sub-array
print("\nsub_arr=",sub_arr)
sub_arr[1,1]=980
print("\nsub Array Modified:",sub_arr)
print("\nOriginal Array Unmodified:",twoD_arr)

Original array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

sub_arr= [[1 2]
 [5 6]]

sub Array Modified: [[  1   2]
 [  5 980]]

Original Array Unmodified: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
#REshaping of Array
import numpy as np
twoD_arr=np.arange(1,10).reshape(3,3)  #Creating a 3x3 array
print("Two Dimensional Array:\n",twoD_arr)

Two Dimensional Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#Reshaping 1D and 2D Arrays
one_D=np.array([1,2,3,4,5,6,7,8,9,10])
print("One Dimensional Array:",one_D)
reshape_oneD=one_D.reshape(2,5)  
print("One D Array reshaping:",reshape_oneD)#Reshaping to 2 rows and 5 columns
two_D=np.array([[1,2,3,4],[5,6,7,8],[1,57,3,8]])
print("Two Dimensional Array:",two_D)
reshape_twoD=two_D.reshape(3,4)  #Reshaping to 3 rows and 4 columns
print("Two D Array reshaping:",reshape_twoD)


One Dimensional Array: [ 1  2  3  4  5  6  7  8  9 10]
One D Array reshaping: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Two Dimensional Array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 1 57  3  8]]
Two D Array reshaping: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 1 57  3  8]]


In [20]:
#unknown Dimension Reshaping
import numpy as np
one_D=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print("One Dimensional Array:",one_D)
reshape_oneD=one_D.reshape(3,-1)  #Using -1 to automatically determine the number of columns
print("One D Array reshaping with unknown dimension:",reshape_oneD)

One Dimensional Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
One D Array reshaping with unknown dimension: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [28]:
#REshaping vs Resizing
import numpy as np
arr=np.array([[1,7,4,1],[456,341,542,2]])
print("OG Array:\n",arr)
arr1=np.resize(arr,(2,2))
print("Resized Array:\n",arr1)  #Resizing the array to 2x2
arr2=arr.reshape(2,4) #Reshaping the array to 2x2
print("Reshaped Array:\n",arr2)  #Reshaping the array to 2x2
print("Reshape does not change the original array, while resize does.")

OG Array:
 [[  1   7   4   1]
 [456 341 542   2]]
Resized Array:
 [[1 7]
 [4 1]]
Reshaped Array:
 [[  1   7   4   1]
 [456 341 542   2]]
Reshape does not change the original array, while resize does.
