In [1]:
#Array Slicing
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print("Array[3:6]=",arr[3:6])
print("Array[1::3]=",arr[1::3])
print("Array[::-1]=",arr[::-1])
print("Array[4::]=",arr[4::])
print("Array[5::-2]=",arr[5::-2])


Array[3:6]= [4 5 6]
Array[1::3]= [2 5 8]
Array[::-1]= [9 8 7 6 5 4 3 2 1]
Array[4::]= [5 6 7 8 9]
Array[5::-2]= [6 4 2]


In [ ]:
#SubArray
import numpy as np
twoD_arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Original array:",twoD_arr)
sub_arr=twoD_arr[:2,:2] #[:2 reprsents values of index{0,0}=1,{0,1}=2of the first row and :2 represents values of index {1,0}=5,{1,1}=6]
print("\nsub_arr=",sub_arr)
sub_arr[0,1]=100
print("\nsub Array Modified:",sub_arr)
print("\nOriginal Array Modified:",twoD_arr)


Original array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

sub_arr= [[1 2]
 [5 6]]

sub Array Modified: [[  1 100]
 [  5   6]]

sOriginal Array Modified: [[  1 100   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [10]:
#Making the copies of the Array 
import numpy as np
twoD_arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Original array:",twoD_arr)
sub_arr=twoD_arr[:2,:2].copy()  #Using copy() to create a copy of the sub-array
print("\nsub_arr=",sub_arr)
sub_arr[1,1]=980
print("\nsub Array Modified:",sub_arr)
print("\nOriginal Array Unmodified:",twoD_arr)

Original array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

sub_arr= [[1 2]
 [5 6]]

sub Array Modified: [[  1   2]
 [  5 980]]

Original Array Unmodified: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
#REshaping of Array
import numpy as np
twoD_arr=np.arange(1,10).reshape(3,3)  #Creating a 3x3 array
print("Two Dimensional Array:\n",twoD_arr)

Two Dimensional Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#Reshaping 1D and 2D Arrays
one_D=np.array([1,2,3,4,5,6,7,8,9,10])
print("One Dimensional Array:",one_D)
reshape_oneD=one_D.reshape(2,5)  
print("One D Array reshaping:",reshape_oneD)#Reshaping to 2 rows and 5 columns
two_D=np.array([[1,2,3,4],[5,6,7,8],[1,57,3,8]])
print("Two Dimensional Array:",two_D)
reshape_twoD=two_D.reshape(3,4)  #Reshaping to 3 rows and 4 columns
print("Two D Array reshaping:",reshape_twoD)


One Dimensional Array: [ 1  2  3  4  5  6  7  8  9 10]
One D Array reshaping: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Two Dimensional Array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 1 57  3  8]]
Two D Array reshaping: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 1 57  3  8]]


In [20]:
#unknown Dimension Reshaping
import numpy as np
one_D=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print("One Dimensional Array:",one_D)
reshape_oneD=one_D.reshape(3,-1)  #Using -1 to automatically determine the number of columns
print("One D Array reshaping with unknown dimension:",reshape_oneD)

One Dimensional Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
One D Array reshaping with unknown dimension: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [28]:
#REshaping vs Resizing
import numpy as np
arr=np.array([[1,7,4,1],[456,341,542,2]])
print("OG Array:\n",arr)
arr1=np.resize(arr,(2,2))
print("Resized Array:\n",arr1)  #Resizing the array to 2x2
arr2=arr.reshape(2,4) #Reshaping the array to 2x2
print("Reshaped Array:\n",arr2)  #Reshaping the array to 2x2
print("Reshape does not change the original array, while resize does.")

OG Array:
 [[  1   7   4   1]
 [456 341 542   2]]
Resized Array:
 [[1 7]
 [4 1]]
Reshaped Array:
 [[  1   7   4   1]
 [456 341 542   2]]
Reshape does not change the original array, while resize does.


In [8]:
#Array Concatenation
import numpy as np
#Concatenation of 1D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concat_arr = np.concatenate((arr1, arr2))
print("Concatenated 1D Array:", concat_arr)  # Concatenating along the first axis (default)
# Concatination of 2D arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]]) 
concat_arr=np.concatenate((arr1,arr2))
print("Concatenated 2D Array:\n", concat_arr)  # Concatenating along the first axis (default)

Concatenated 1D Array: [1 2 3 4 5 6]
Concatenated 2D Array:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [12]:
#np vstack and hstack
import numpy as np
# Vertical stacking of 1D arrays
arr1=np.array([1,2,3,4])
arr2=np.array([[5,6,73,5],[3,87,56,78]])
stac_v=np.vstack([arr1,arr2])
print("Vertical Stacking is:\n",stac_v) # Stacking along the first axis (rows)
# Horizontal stacking of 1D arrays
arr1=np.array([[1,4],[5,7]])
arr2=np.array([[5,6,73,5],[3,87,56,78]])
stac_h=np.hstack([arr1,arr2])
print("Horizontal Stacking is:\n",stac_h)  # Stacking along the second axis (columns)



Vertical Stacking is:
 [[ 1  2  3  4]
 [ 5  6 73  5]
 [ 3 87 56 78]]
Horizontal Stacking is:
 [[ 1  4  5  6 73  5]
 [ 5  7  3 87 56 78]]


In [6]:
#Appending Arrays
import numpy as np
# Appending to a 1D array
arr1=np.array([1,75,889,34,2344,5342,89])
arr2=np.array([342,346,123,78,46,35])
apeended_Arr=np.append(arr1,arr2)
print("Appended 1D Array:", apeended_Arr)  # Appending to a 1D array
# Appending to a 2D Array
arr=np.array([[1,3,64,23],[234,43,67,43]])
arr1=np.array([[234,456,123,345],[245,52,5,21]])
concated_arr=np.concatenate((arr,arr1),axis=1) # Concatenating along the second axis (columns)
print("Appended 2D Array:", concated_arr)

Appended 1D Array: [   1   75  889   34 2344 5342   89  342  346  123   78   46   35]
Appended 2D Array: [[  1   3  64  23 234 456 123 345]
 [234  43  67  43 245  52   5  21]]


In [11]:
#splitting Arrays
import numpy as np
# Vsplitting Arrays
arr=np.arange(16).reshape(4,4)
print("Original Array:\n", arr)
# Splitting the array into two equal parts
vsplit_arr=np.vsplit(arr,2)
print("Vertically Split Array:\n", vsplit_arr)  # Splitting the array vertically into two parts
# Hsplitting Arrays
hsplit_arr=np.hsplit(arr,2)
print("Horizontally Split Array:\n", hsplit_arr)  # Splitting the array horizontally into two parts

Original Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Vertically Split Array:
 [array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
Horizontally Split Array:
 [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [13]:
#Numpy Broadcasting
import numpy as np
arr=np.ones((2,2))
print("Dimension of the Arr:",np.ndim(arr))
arr2=np.random.random((2,2))
print("Dimesnion of the Arr2:",np.ndim(arr2))
result=arr+arr2
print("Result of Broadcasting:\n", result)  # Broadcasting the addition of two arrays with different shapes
# Broadcasting allows numpy to perform operations on arrays of different shapes by automatically expanding the smaller array to match the shape of the larger one.

Dimension of the Arr: 2
Dimesnion of the Arr2: 2
Result of Broadcasting:
 [[1.92544204 1.63907245]
 [1.25163065 1.50352434]]


In [1]:
#Array Insertion
import numpy as np
arr=np.array([1,2,3,4,5])
print("Array before insertion:", arr)  # Original array
arr2=np.insert(arr,2,10)# arr is the original array, 2 is the index where 10 will be inserted
print("Array after insertion:", arr2)  # Array after inserting 10 at index 2

Array before insertion: [1 2 3 4 5]
Array after insertion: [ 1  2 10  3  4  5]


In [ ]:
#Array Deletion
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print("Array before deletion:", arr)  # Original array
arr2 = np.delete(arr, 2)  # Deletes the element at index 2
print("Array after deletion:", arr2)  # Array after deleting the element at index 2

In [2]:
#Check if array is empty
import numpy as np
arr = np.array([])  # Creating an empty array
if arr.size==0:
    print("The array is empty.")
else:
    print("The array is not empty.")


The array is empty.


In [4]:
#Index Value in Array
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
index = np.where(arr==4)  # Finding the index of the value 4
print("Index of value 4 in the array:", index)

Index of value 4 in the array: (array([3]),)


In [5]:
#Sorting in Numpy
import numpy as np
arr = np.array([3, 1, 4, 2, 5])
sorted_arr = np.sort(arr)  # Sorting the array in ascending order
print("Sorted Array:", sorted_arr)  # Output: [1 2 3 4 5]

Sorted Array: [1 2 3 4 5]
