In [1]:
#Array  Sum
import numpy as np      
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
sum_arr=np.add(arr1,arr2)
print("Sum of two arrays:", sum_arr)  # Adding two arrays element-wise

Sum of two arrays: [ 7  9 11 13 15]


In [2]:
#Array minimum
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
min_arr=np.minimum(arr1,arr2)
print("Minimum of two arrays:", min_arr)  # Finding the minimum element-wise

Minimum of two arrays: [1 2 3 4 5]


In [5]:
#Array Maximum
import numpy as np
arr=np.array([[1,2,3,5],[165,75,77,3]])
arr1=np.array([[6,7,8,9],[10,11,12,43]])
np_max=np.maximum(arr,arr1)
print("Maximum of two arrays:", np_max)  # Finding the maximum element-wise

Maximum of two arrays: [[  6   7   8   9]
 [165  75  77  43]]


In [6]:
#Array Mean
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
mean_arr=np.mean([arr1,arr2], axis=0)
print("Mean of two arrays:", mean_arr)  # Finding the mean element-wise

Mean of two arrays: [3.5 4.5 5.5 6.5 7.5]


In [7]:
#Array Median
arr=np.array([1,654,876,233])
arr2=np.array([522,653,645,43])
median_arr=np.median([arr,arr2])
print("Median of two arrays:", median_arr)  # Finding the median element-wise

Median of two arrays: 583.5


In [10]:
#Numpy corrcoetion
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, -7, -8, 9,-10])
correlation = np.corrcoef(arr1, arr2)
print("Correlation coefficient between two arrays:", correlation)  # Finding the correlation coefficient

Correlation coefficient between two arrays: [[ 1.         -0.28736848]
 [-0.28736848  1.        ]]


In [ ]:
#Numpy Standard Deviation
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([06, -7, -8, 9,-10])
std_dev = np.std([arr1, arr2], axis=0)
print("Standard Deviation of two arrays:", std_dev)  # Finding the standard deviation element-wise

Standard Deviation of two arrays: [2.5 4.5 5.5 2.5 7.5]


In [ ]:
 #Logical Operations
import numpy as np 
arr1= np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr1[arr1>5]) 
print(arr1[(arr1>6)|(arr1%2==0)]) #OR operation


[ 6  7  8  9 10]
[ 2  4  6  7  8  9 10]


In [23]:
#Normalization
import numpy as np
arr=np.array([1,43,23,56,54,66])
nomalized_arr=((arr-min(arr))/(max(arr)-min(arr)))
print("Normalized Array:", nomalized_arr)  # Normalizing the array

Normalized Array: [0.         0.64615385 0.33846154 0.84615385 0.81538462 1.        ]
