In [10]:
#Creating array
import numpy as np
#1d Array
print("Ärray")
arr=np.array([1,2,3,4])
print(arr)
#2D Array
print("\n2D Ärray")
arr1=np.array([[15,42,43,24],[22,43,54,55]])
print(arr1)     
print("\n3D Ärray")     
arr2=np.array([[[1,2,3,4],[23,45,34,2,],[123,45,32,56,],[123,564,456,775]]])
print(arr2)

Ärray
[1 2 3 4]

2D Ärray
[[15 42 43 24]
 [22 43 54 55]]

3D Ärray
[[[  1   2   3   4]
  [ 23  45  34   2]
  [123  45  32  56]
  [123 564 456 775]]]


In [1]:
import numpy as np
a=np.array([(1,2,3)])
print(a)
a=np.zeros((2,4))
print(a)
b=np.ones((2,2))
print(b)
a=np.array([(1,2,3,4)])
b=np.empty(a.shape)
print(b)

[[1 2 3]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[1. 1. 1. 1.]]


In [ ]:
# Empty Function
import numpy as np
# Create a 2x3 empty array of integers
empty_array = np.empty((2, 3), dtype=str)
print(empty_array)

[['' '' '']
 ['' '' '']]


In [ ]:
#Full Function
sub=np.full((2,2),dtype=int,fill_value=3)
print(sub)

[[3 3]
 [3 3]]


In [ ]:
# Eye Function that is identity fucntion where diagonal are 1 and rest other values are 0 in matrix.
import numpy as np
# Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("3x3 Identity Matrix:")
print(identity_matrix)

# Create a 4x5 matrix with ones on the main diagonal
matrix_main_diag = np.eye(4, 5)
print("\n4x5 Matrix with ones on the main diagonal:")
print(matrix_main_diag)

# Create a 4x4 matrix with ones on the first upper diagonal (k=1)
matrix_upper_diag = np.eye(4, k=1)
print("\n4x4 Matrix with ones on the first upper diagonal:")
print(matrix_upper_diag)

# Create a 4x4 matrix with ones on the first lower diagonal (k=-1)
matrix_lower_diag = np.eye(4, k=-1)
print("\n4x4 Matrix with ones on the first lower diagonal:")
print(matrix_lower_diag)

3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4x5 Matrix with ones on the main diagonal:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]

4x4 Matrix with ones on the first upper diagonal:
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]

4x4 Matrix with ones on the first lower diagonal:
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [ ]:
#Linespace function
import numpy as np
num=np.linspace(0,5,3)
print(num)

[0.  2.5 5. ]


In [6]:
#Linespace function 
import numpy as np
# Create an array of 10 evenly spaced numbers between 0 and 1
linspace_array = np.linspace(0, 1, 10)
print("Array of 10 evenly spaced numbers between 0 and 1:")
print(linspace_array)

# Create an array of 5 evenly spaced numbers between -5 and 5, excluding the endpoint
linspace_no_endpoint = np.linspace(-5, 5, 5, endpoint=False)
print("\nArray of 5 evenly spaced numbers between -5 and 5 (excluding endpoint):")
print(linspace_no_endpoint)

# Create an array and get the step size
linspace_with_step, step_size = np.linspace(0, 10, 5, retstep=True)
print("\nArray with step size:")
print(linspace_with_step)
print("Step size:", step_size)

Array of 10 evenly spaced numbers between 0 and 1:
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]

Array of 5 evenly spaced numbers between -5 and 5 (excluding endpoint):
[-5. -3. -1.  1.  3.]

Array with step size:
[ 0.   2.5  5.   7.5 10. ]
Step size: 2.5


In [8]:
#Reshape Function to specify the shape of the created array.
import numpy as np
a=np.array([(1,2,3,4,)])
a=np.reshape(a,(2,2))
print(a)

[[1 2]
 [3 4]]


In [ ]:
#Reshape function with differnt dimensional Array
import numpy as np
# Create a 1D array
arr = np.array([1, 2, 3, 4, 5, 6])
print("Original array:")
print(arr)
print("Shape:", arr.shape)

# Reshape the 1D array into a 2x3 array
reshaped_arr = np.reshape(arr, (2, 3))
print("\nReshaped array (2x3):")
print(reshaped_arr)
print("Shape:", reshaped_arr.shape)

# Reshape the 1D array into a 3x2 array using -1
reshaped_arr_auto = np.reshape(arr, (3, -1))
print("\nReshaped array (3x2 using -1):")
print(reshaped_arr_auto)
print("Shape:", reshaped_arr_auto.shape)

# Reshape the 1D array into a 2x3 array and modify an element
reshaped_arr_modify = np.reshape(arr, (2, 3))
reshaped_arr_modify[0, 0] = 100
print("\nReshaped array after modification:")
print(reshaped_arr_modify)
print("Original array after modification:")
print(arr)

Original array:
[1 2 3 4 5 6]
Shape: (6,)

Reshaped array (2x3):
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

Reshaped array (3x2 using -1):
[[1 2]
 [3 4]
 [5 6]]
Shape: (3, 2)

Reshaped array after modification:
[[100   2   3]
 [  4   5   6]]
Original array after modification:
[100   2   3   4   5   6]


In [ ]:
#Arange Function
import numpy as np
b=np.arange(3)
print(b)
# Create an array using np.arange with start and stop values
c = np.arange(2, 8)
print(c)
# Create an array using np.arange with start, stop, and step values
d = np.arange(1, 10, 2)
print(d)

[0 1 2]
[2 3 4 5 6 7]
[1 3 5 7 9]


In [ ]:
#Transpose Function
import numpy as np
# Create a sample matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("Original Matrix:")
print(matrix)

# Get the transpose using the .T attribute
transpose_matrix_T = matrix.T
print("\nTranspose using .T:")
print(transpose_matrix_T)

# Get the transpose using np.transpose()
transpose_matrix_func = np.transpose(matrix)
print("\nTranspose using np.transpose():")
print(transpose_matrix_func)

# Example with a higher-dimensional array
arr_3d = np.arange(12).reshape((2, 3, 2))
print("\nOriginal 3D array:")
print(arr_3d)

# Transpose the 3D array (swaps axes 0 and 1 by default)
transpose_arr_3d = arr_3d.T
print("\nTranspose of 3D array (.T):")
print(transpose_arr_3d)

# Transpose the 3D array by specifying axis order
transpose_arr_3d_axes = np.transpose(arr_3d, axes=(1, 0, 2))
print("\nTranspose of 3D array (np.transpose with axes=(1, 0, 2)):")
print(transpose_arr_3d_axes)