In [1]:
#Inserting elements in rows and columns of 2d array.
import numpy as np
arr=np.arange(12).reshape(4,3)
print('\n\n2D arr:\n',arr)
print('\n\nShape:',arr.shape)
arr=np.insert(arr,1,5,axis=1)
print('\n\n Array After insertion:',arr)
print('\n\nShape:',arr.shape)
arr=np.insert(arr,2,6,axis=0)
print('\n\n Array After insertion:',arr)
print('\n\nShape:',arr.shape)



2D arr:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


Shape: (4, 3)


 Array After insertion: [[ 0  5  1  2]
 [ 3  5  4  5]
 [ 6  5  7  8]
 [ 9  5 10 11]]


Shape: (4, 4)


 Array After insertion: [[ 0  5  1  2]
 [ 3  5  4  5]
 [ 6  6  6  6]
 [ 6  5  7  8]
 [ 9  5 10 11]]


Shape: (5, 4)
